# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Pathway to Arabic Study Group
site_description: "A reference site for the students of Pathway to Arabic website."
site_url: "https://nqcm.github.io/pathway-to-arabic-study-group/"
site_author: "Naveera Ashraf"

copyright: "© All rights reserved - naveeraashraf.com"

repo_name: "nqcm/pathway-to-arabic-study-group"
repo_url: "https://github.com/nqcm/pathway-to-arabic-study-group"

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - toc:
      title: On this page
      toc_depth: 2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nqcm/pathway-to-arabic-study-group
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/niqabicodermum
    - icon: fontawesome/brands/linkedin
      link: https://za.linkedin.com/in/naveera-ashraf
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/niqabi.coder.mum/

nav:
  - About: index.md
  - Surah Yusuf Sessions: surah-yusuf-sessions/index.md
  - Surah Al-Hujuraat Sessions: surah-alhujuraat-sessions/index.md
  - Topics: topics/index.md

theme:
  name: material
  font:
    text: Noto Naskh Arabic
  icon:
    annotation: material/plus-circle
  palette:
    scheme: slate
    primary: indigo
    accent: indigo

  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.share

plugins:
  - social
  - search:
      lang:
        - eng
        - ar

extra_css:
  - stylesheets/extra.css
